# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevopsRegister',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'devops_register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestServer',
            fields=[
                ('instance_id', models.CharField(db_column='instance_ID', max_length=255, primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=255)),
                ('out_net', models.CharField(max_length=255)),
                ('inner_net', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('createtime', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('sys', models.CharField(db_column='SYS', max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('deadtime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_server',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateTestServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_people', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('sys_variety', models.CharField(max_length=255)),
                ('update_time', models.CharField(max_length=255)),
                ('except_info', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'update_test_server',
                'managed': False,
            },
        ),
    ]
