# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'index_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'index_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexBookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'index_book_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Membership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_column='instance_ID', max_length=255, unique=True)),
                ('instance_name', models.CharField(max_length=255)),
                ('out_net', models.CharField(max_length=255)),
                ('inner_net', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('createtime', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('sys', models.CharField(db_column='SYS', max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('deadtime', models.CharField(max_length=255)),
                ('bandwidth', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'online_server',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Person',
                'managed': False,
            },
        ),
    ]
